version: 2
build:
  os: ubuntu-lts-latest
  tools:
    python: "3"
  jobs:
    pre_build:
      - pybabel compile -f -d locale
python:
  install:
    - requirements: docs/requirements.txt
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
