FROM node:20 AS build-stage

WORKDIR /workdir

COPY frontend/package*.json ./
RUN npm ci --ignore-scripts

COPY . .

WORKDIR /workdir/frontend
RUN npx tsc && npx vite build

FROM nginxinc/nginx-unprivileged:latest AS production-stage
USER root
ARG client_max_body_size
COPY --from=build-stage --chown=nginx:root /workdir/frontend/dist /usr/share/nginx/html
COPY --chown=nginx:root frontend/default.conf /etc/nginx/conf.d/default.conf
USER nginx
