"""credit provider change

Revision ID: 3862ac06c19d
Revises: 7b3c4836cfe5
Create Date: 2023-06-29 13:35:35.037973

"""
import sqlalchemy as sa
import sqlmodel  # added
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3862ac06c19d"
down_revision = "7b3c4836cfe5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "credit_product",
        sa.Column("lower_limit", sa.DECIMAL(precision=16, scale=2), nullable=False),
        sa.Column("upper_limit", sa.DECIMAL(precision=16, scale=2), nullable=False),
        sa.Column(
            "type", sa.Enum("LOAN", "CREDIT_LINE", name="credit_type"), nullable=True
        ),
        sa.Column(
            "required_document_types",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "other_fees_total_amount", sa.DECIMAL(precision=16, scale=2), nullable=False
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "other_fees_description", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("more_info_link", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("lender_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["lender_id"],
            ["lender.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "application", sa.Column("credit_product_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "application", "credit_product", ["credit_product_id"], ["id"]
    )
    op.add_column(
        "lender",
        sa.Column(
            "credit_Product",
            sa.Enum("LOAN", "CREDIT_LINE", name="credit_type"),
            nullable=True,
        ),
    )
    op.drop_column("lender", "borrower_type_preferences")
    op.drop_column("lender", "limits_preferences")
    op.drop_constraint("message_lender_id_fkey", "message", type_="foreignkey")
    op.drop_column("message", "lender_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "message",
        sa.Column("lender_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "message_lender_id_fkey", "message", "lender", ["lender_id"], ["id"]
    )
    op.add_column(
        "lender",
        sa.Column(
            "limits_preferences",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "lender",
        sa.Column(
            "borrower_type_preferences",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("lender", "credit_Product")
    op.drop_constraint(None, "application", type_="foreignkey")
    op.drop_column("application", "credit_product_id")
    op.drop_table("credit_product")
    # ### end Alembic commands ###
