"""
application credit_prodict_id index

Revision ID: 43b0e52f761d
Revises: d77ac01b9718
Create Date: 2024-10-08 00:25:31.376994

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "43b0e52f761d"
down_revision = "d77ac01b9718"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_application_credit_product_id"), "application", ["credit_product_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_application_credit_product_id"), table_name="application")
    # ### end Alembic commands ###
