"""borrower is_msme field

Revision ID: 8a775f48bf88
Revises: d4bb1f0964ed
Create Date: 2024-07-22 16:02:46.040694

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy import true

# revision identifiers, used by Alembic.
revision = "8a775f48bf88"
down_revision = "d4bb1f0964ed"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("borrower", sa.Column("is_msme", sa.Boolean(), nullable=False, server_default=true()))


def downgrade() -> None:
    op.drop_column("borrower", "is_msme")
