"""make JSON nonnullable

Revision ID: beaafd626a26
Revises: 20e0ff589a61
Create Date: 2024-08-19 16:27:02.124642

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "beaafd626a26"
down_revision = "20e0ff589a61"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "application", "calculator_data", existing_type=postgresql.JSON(astext_type=sa.Text()), nullable=False
    )
    op.alter_column(
        "application",
        "borrower_declined_preferences_data",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "application", "borrower_declined_data", existing_type=postgresql.JSON(astext_type=sa.Text()), nullable=False
    )
    op.alter_column(
        "application", "secop_data_verification", existing_type=postgresql.JSON(astext_type=sa.Text()), nullable=False
    )
    op.alter_column(
        "application", "lender_approved_data", existing_type=postgresql.JSON(astext_type=sa.Text()), nullable=False
    )
    op.alter_column(
        "application", "lender_rejected_data", existing_type=postgresql.JSON(astext_type=sa.Text()), nullable=False
    )
    op.alter_column("application_action", "data", existing_type=postgresql.JSON(astext_type=sa.Text()), nullable=False)
    op.alter_column("award", "payment_method", existing_type=postgresql.JSON(astext_type=sa.Text()), nullable=False)
    op.alter_column("award", "missing_data", existing_type=postgresql.JSON(astext_type=sa.Text()), nullable=False)
    op.alter_column(
        "award", "source_data_contracts", existing_type=postgresql.JSON(astext_type=sa.Text()), nullable=False
    )
    op.alter_column(
        "award", "source_data_awards", existing_type=postgresql.JSON(astext_type=sa.Text()), nullable=False
    )
    op.alter_column("borrower", "missing_data", existing_type=postgresql.JSON(astext_type=sa.Text()), nullable=False)
    op.alter_column("borrower", "source_data", existing_type=postgresql.JSON(astext_type=sa.Text()), nullable=False)
    op.alter_column(
        "credit_product",
        "required_document_types",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "statistic",
        "data",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=False,
        existing_server_default=sa.text("'{}'::json"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "statistic",
        "data",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=True,
        existing_server_default=sa.text("'{}'::json"),
    )
    op.alter_column(
        "credit_product",
        "required_document_types",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column("borrower", "source_data", existing_type=postgresql.JSON(astext_type=sa.Text()), nullable=True)
    op.alter_column("borrower", "missing_data", existing_type=postgresql.JSON(astext_type=sa.Text()), nullable=True)
    op.alter_column("award", "source_data_awards", existing_type=postgresql.JSON(astext_type=sa.Text()), nullable=True)
    op.alter_column(
        "award", "source_data_contracts", existing_type=postgresql.JSON(astext_type=sa.Text()), nullable=True
    )
    op.alter_column("award", "missing_data", existing_type=postgresql.JSON(astext_type=sa.Text()), nullable=True)
    op.alter_column("award", "payment_method", existing_type=postgresql.JSON(astext_type=sa.Text()), nullable=True)
    op.alter_column("application_action", "data", existing_type=postgresql.JSON(astext_type=sa.Text()), nullable=True)
    op.alter_column(
        "application", "lender_approved_data", existing_type=postgresql.JSON(astext_type=sa.Text()), nullable=True
    )
    op.alter_column(
        "application", "lender_rejected_data", existing_type=postgresql.JSON(astext_type=sa.Text()), nullable=True
    )
    op.alter_column(
        "application", "secop_data_verification", existing_type=postgresql.JSON(astext_type=sa.Text()), nullable=True
    )
    op.alter_column(
        "application", "borrower_declined_data", existing_type=postgresql.JSON(astext_type=sa.Text()), nullable=True
    )
    op.alter_column(
        "application",
        "borrower_declined_preferences_data",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "application", "calculator_data", existing_type=postgresql.JSON(astext_type=sa.Text()), nullable=True
    )
    # ### end Alembic commands ###
