"""
award id borrower id nonnullable

Revision ID: d9b564fd6859
Revises: eaef8e99aee2
Create Date: 2024-08-23 15:38:20.028504

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d9b564fd6859"
down_revision = "eaef8e99aee2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("application", "award_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("application", "borrower_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("application", "borrower_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("application", "award_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
