"""borrowerdocument.type nonnullable

Revision ID: eaef8e99aee2
Revises: d5f6a158acf0
Create Date: 2024-08-19 23:57:22.893217

"""

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "eaef8e99aee2"
down_revision = "d5f6a158acf0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "borrower_document",
        "type",
        existing_type=postgresql.ENUM(
            "INCORPORATION_DOCUMENT",
            "SUPPLIER_REGISTRATION_DOCUMENT",
            "BANK_NAME",
            "BANK_CERTIFICATION_DOCUMENT",
            "FINANCIAL_STATEMENT",
            "SIGNED_CONTRACT",
            "SHAREHOLDER_COMPOSITION",
            "CHAMBER_OF_COMMERCE",
            "THREE_LAST_BANK_STATEMENT",
            name="borrower_document_type",
        ),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "borrower_document",
        "type",
        existing_type=postgresql.ENUM(
            "INCORPORATION_DOCUMENT",
            "SUPPLIER_REGISTRATION_DOCUMENT",
            "BANK_NAME",
            "BANK_CERTIFICATION_DOCUMENT",
            "FINANCIAL_STATEMENT",
            "SIGNED_CONTRACT",
            "SHAREHOLDER_COMPOSITION",
            "CHAMBER_OF_COMMERCE",
            "THREE_LAST_BANK_STATEMENT",
            name="borrower_document_type",
        ),
        nullable=True,
    )
    # ### end Alembic commands ###
